server:
  port: 10003
spring:
  application:
    name: tues-erc20

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(DI9iXNL4PUxC4zOhd4I00cbzB0TLicu9eb3RHNio4dDm6uinKLOhzuae0O73E6ImWCrcvSoc466PwyEkz5GP9kgUPcx+EGtSMFGiE4eLHfcQVz4FNP5cIA3AiFsnmClLLCPwrPwOcmi5ABG7xVfY4UyIrVAwBjZz9FvbZ4+2x2T1g0JH01x/EPC2J50xmqG6)
    username: ENC(le89BOO33fezSsQl/4kzpg==)
    password: ENC(K6vVvNk53bp61G9ncufyZm9qes75AwEO)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ethereum:
  currencyName: NICE
  nodeurl: ENC(NyrPV0J3triDCbj+QidgOihNvV5H5zuuk3VGCDtUyOI8QIHvUJSgdOc3vnNkeT6h9xx/DVz5tmKipaz3TV44cam23HHLnU30) #节点地址,infura需包含PROJECT_ID
  keystorepath: D:/code/keystore/erc20
  keystorepassword: 123456
jasypt:
  encryptor:
    password: yoursecret #配置EncryptPropertiesUtils工具类里填写的秘钥，最好在命令行注入参数
