server:
  port: 10002
spring:
  application:
    name: tues-eth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ob-dev.huatianyunce.com.cn:2881/htyc_payment?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: payment@htyc
    password: Z]]8,AbYtgHdDsCT!i#[*H|1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

sol:
  currencyName: SOL
  keystorepath: D:/code/keystore
  keystorepassword: 123456
jasypt:
  encryptor:
    password: yoursecret #配置EncryptPropertiesUtils工具类里填写的秘钥，最好在命令行注入参数
